#getting image from quay.io

#labels and environment variables
LABEL cubix.homework.owner="Homework Containerization" Author="Balázs Császár"
ENV CUBIX_HOMEWORK=Balazs Csaszar
ENV APP_DEFAULT_MESSAGE=Hello Homework2